export const ANALYTICS_ACTIONS = {
    CODE_CHANGE: "CODE_CHANGE",
    TYPING: "TYPING",
    FILE_CREATED: "FILE_CREATED",
    FILE_DELETED: "FILE_DELETED",
    FILE_RENAMED: "FILE_RENAMED",
    MESSAGE_SENT: "MESSAGE_SENT",
    DRAWING_UPDATE: "DRAWING_UPDATE",
    COMPILER_STATUS: "COMPILER_STATUS",
  };